apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: web
  labels:
    app: employees
spec:
  containers:
    - name: webapp
      image: 781568375230.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "mysql-service.mysql.svc.cluster.local"       
        - name: DBPORT
          value: "3306"             
        - name: DBUSER
          value: "root" # Using root since your docker command uses root
        - name: DBPWD
          value: "password"
        - name: DATABASE
          value: "employees"
